spring:
  application:
    name: transacao-simplificada

  datasource:
    url: jdbc:postgresql://localhost:5433/picpay_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
api:
  url:
    authorize: https://util.devi.tools/api/v2/authorize
    notify: https://util.devi.tools/api/v1/notify

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
